### ISSUE TITLE
Excluding the gh-pages branch from Circle CI

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#2133]
Ideally, without needing to exclude the branch for each job separately. See https://discuss.circleci.com/t/excluding-a-branch-from-ci/17811

We need this because otherwise we get an email about the workflow error from Circle CI for each commit to gh-pages.

**Comment by nikohansen** [comment]
Writing in the yaml file before jobs:
```
on:
  push:
    branches-ignore:
      - 'gh-pages'
```
may work
